# Environmental inputs 

So far we have largely discussed developmental patterning processes as if they are either occurring under constant environmental conditions or as if environmental conditions have no effect. A minor exception to this is the discussion on robustness of patterning under morphogen gradients, where differences in input of maternal resources, which in turn may depend on food conditions, may impact embryo size and hence scaling is required.  

 
In contrast to our discussion so far, environmental conditions may have a major impact on developmental processes. This ranges from the effect of temperature on the body sizes of fruitflies and butterflies, and on the gender of hatching sea turtles, nutritional effects on ant size and worker function to the complete reshaping of organs, organ positioning and body plans in plants. Indeed, while for animals symmetry and scaling are essential for mobility, for plants adaptation to the conditions they find themselves in is of key importance, making developmental plasticity more pervasive in plant development.  In the practical we are going to investigate temperature induced leaf hyponasty, in which plants develop leaves with longer petioles (stems) and smaller blades (leaf surface itself) that are positioned in a more upright angle, investigating the adaptive value of this developmental plasticity. 

 
Apart from the question whether plasticity of a developmental process is adaptive, a major question is how this plasticity can be united with robustness. That is, how certain aspects of development can be adjusted, while other aspects can be maintained (i.e. the plant still makes a leaf, that has still a top, bottom, stomata veins, etc but other things are allowed to vary). Additionally, a question is how the networks that drive developmental patterning and e.g. cell fate decisions (Part 3) are integrated with networks that sense, process and combine various environmental signals to decide how these developmental processes are to be adjusted. This will be discussed in the lecture. 


In addition to developmental processes, also physiology, behavior and evolution of course depend on environmental conditions. Examples of the latter two will be discussed in Part 5. 