# Modeling life {#modeling .unnumbered}

This website accompanies the Modeling Life course at Utrecht University. It primarily serves as a central hub for all the practicals (werkcolleges), with the necessarily files, links and other resources for each day. 

Each practical has its own page containing background explanations, code snippets, and questions that are designed for you to learn about the models. Most of these exercises build directly on the lectures, allowing you to explore biological questions—such as how morphogen gradients form, how spatial patterns emerge, or how cells evolve to "stick together".

You can navigate the site using the sidebar or the left. The [General Course Info](general.qmd) section outlines the general course info (exams, learning goals, etc.). You can also find the [Schedule](schedule.qmd) on this website. The individual practicals sections provides detailed instructions for each day. In the second part of the course you will get even more experience doing things yourself by working on a mini-project. 

We hope you’ll use this website actively. There's lots to read, simulate, modify, and explore.

:::{style="color:red;"}
*Note: the Modeling Life course is new. This website is to help you, but is by no means perfect. Please let us know if you see any mistakes, typo's or other issues. Any constructive feedback on how to make things better and easier for you is always welcome.*
:::

